// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8BfxcLQDrzO4TaJt8uUjYdGW7RrT2A4c',
    appId: '1:336571036333:web:e88112c5774d042ff04c24',
    messagingSenderId: '336571036333',
    projectId: 'home-finder-a3b5b',
    authDomain: 'home-finder-a3b5b.firebaseapp.com',
    storageBucket: 'home-finder-a3b5b.firebasestorage.app',
    measurementId: 'G-6GKLSZB3ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKCZnNTLjtePUBG66mbK58hVrCUsF3tcM',
    appId: '1:336571036333:android:52a13c8bee205107f04c24',
    messagingSenderId: '336571036333',
    projectId: 'home-finder-a3b5b',
    storageBucket: 'home-finder-a3b5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUNfsbTtGrTcQeKcE0JFzBFWTDzmH7TAQ',
    appId: '1:336571036333:ios:93e0f7c7c856598bf04c24',
    messagingSenderId: '336571036333',
    projectId: 'home-finder-a3b5b',
    storageBucket: 'home-finder-a3b5b.firebasestorage.app',
    iosBundleId: 'com.example.homeFind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUNfsbTtGrTcQeKcE0JFzBFWTDzmH7TAQ',
    appId: '1:336571036333:ios:93e0f7c7c856598bf04c24',
    messagingSenderId: '336571036333',
    projectId: 'home-finder-a3b5b',
    storageBucket: 'home-finder-a3b5b.firebasestorage.app',
    iosBundleId: 'com.example.homeFind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8BfxcLQDrzO4TaJt8uUjYdGW7RrT2A4c',
    appId: '1:336571036333:web:12b72377b31541e9f04c24',
    messagingSenderId: '336571036333',
    projectId: 'home-finder-a3b5b',
    authDomain: 'home-finder-a3b5b.firebaseapp.com',
    storageBucket: 'home-finder-a3b5b.firebasestorage.app',
    measurementId: 'G-023W0DQSD4',
  );
}
